### ISSUE TITLE
Blank plot with numpy v2

### ISSUE THREAD

**Issue by CubeOvO** [gaogaotiantian/pitch-visualizer#5]
See [this issue](https://github.com/YannickJadoul/Parselmouth/issues/125) on the Parselmouth page.

In this case, output of ```pitch.xs()``` (i.e. x-axis values) within ```animate()``` is faulty, so the plot is blank
Should be fixed by specifying ```numpy<2``` in ```requirements.txt```

**Comment by mind-dance** [comment]
thx! You have helped me a lot.
